#!/usr/bin/env bash
# Resolve or prompt for target IDE; writes agent/ide-target.
set -euo pipefail

usage() {
  echo "Usage: select-ide.sh [--ide cursor|claude|codex] [--other NAME] [--non-interactive]"
  echo "  Env: WORK_AGENT_IDE, WORK_AGENT_IDE_OTHER (for D. Other)"
}

IDE_CHOICE=""
IDE_OTHER=""
NON_INTERACTIVE=false
CLI_SPECIFIED=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ide) IDE_CHOICE="$2"; CLI_SPECIFIED=true; shift 2 ;;
    --other) IDE_OTHER="$2"; IDE_CHOICE="other"; CLI_SPECIFIED=true; shift 2 ;;
    --non-interactive) NON_INTERACTIVE=true; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

if [[ -z "$IDE_CHOICE" && "$CLI_SPECIFIED" != true && -n "${WORK_AGENT_IDE:-}" ]]; then
  IDE_CHOICE="$WORK_AGENT_IDE"
fi
if [[ -z "$IDE_OTHER" && -n "${WORK_AGENT_IDE_OTHER:-}" ]]; then
  IDE_OTHER="$WORK_AGENT_IDE_OTHER"
fi

if [[ -z "$IDE_CHOICE" ]] && [[ "$NON_INTERACTIVE" != true ]] && [[ -t 0 ]]; then
  echo ""
  echo "Which AI coding tool are you using for this Work Agent?"
  echo "  A) Claude (Claude Code / Claude desktop project)"
  echo "  B) Codex"
  echo "  C) Cursor"
  echo "  D) Other"
  echo ""
  read -r -p "Enter A, B, C, D, or name (cursor/claude/codex): " pick
  pick="$(echo "$pick" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')"
  case "$pick" in
    a|claude) IDE_CHOICE="claude" ;;
    b|codex) IDE_CHOICE="codex" ;;
    c|cursor) IDE_CHOICE="cursor" ;;
    d|other)
      read -r -p "Other tool name (e.g. windsurf): " IDE_OTHER
      IDE_CHOICE="other"
      ;;
    cursor|claude|codex) IDE_CHOICE="$pick" ;;
    *)
      if [[ -n "$pick" ]]; then
        IDE_OTHER="$pick"
        IDE_CHOICE="other"
      else
        IDE_CHOICE="cursor"
      fi
      ;;
  esac
fi

if [[ -z "$IDE_CHOICE" ]]; then
  IDE_CHOICE="cursor"
fi

IDE_KEY="$IDE_CHOICE"
IDE_LABEL=""
IDE_DIR=""

case "$IDE_KEY" in
  cursor)
    IDE_LABEL="Cursor"
    IDE_DIR=".cursor"
    ;;
  claude)
    IDE_LABEL="Claude"
    IDE_DIR=".claude"
    ;;
  codex)
    IDE_LABEL="Codex"
    IDE_DIR=".codex"
    ;;
  other)
    if [[ -z "$IDE_OTHER" ]]; then
      IDE_OTHER="other"
    fi
    safe="$(echo "$IDE_OTHER" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-' | sed 's/^-//;s/-$//')"
    [[ -z "$safe" ]] && safe="other"
    IDE_LABEL="$IDE_OTHER"
    IDE_DIR=".$safe"
    IDE_KEY="$safe"
    ;;
  *)
    echo "Error: unknown IDE '$IDE_CHOICE'. Use cursor, claude, codex, or --other NAME."
    exit 1
    ;;
esac

ROOT="${WORK_AGENT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
TARGET_FILE="$ROOT/agent/ide-target"

mkdir -p "$ROOT/agent"
cat > "$TARGET_FILE" <<EOF
# Generated by onboard / select-ide.sh — switching IDE: re-run ./onboard-agent-dan
IDE=$IDE_KEY
IDE_DIR=$IDE_DIR
IDE_LABEL=$IDE_LABEL
EOF

echo "→ IDE: $IDE_LABEL (assets dir: $IDE_DIR)"
export WORK_AGENT_IDE="$IDE_KEY"
export WORK_AGENT_IDE_DIR="$IDE_DIR"
